### ISSUE TITLE
Map Features do not toggle on/off

### ISSUE THREAD

**Issue by flow-enol** [facebookincubator/RapiD#552] opened 2022-08-18 21:35 UTC
### Description

The feature buttons on the right don't display pop-up text bubbles. 
The "Map Data" menu has a few issues:
(1) "Map Features" do not toggle on/off.
(2) "Highlight Changes" option (under "Style Options") doesn't work when toggled on.
(3) It's hotkey (U) doesn't open the menu (*Found out that 'F' is the hotkey in RapID this could be confusing for users*).

(1) <img width="1913" alt="image" src="https://user-images.githubusercontent.com/96031300/185494573-84c60bf1-2409-4473-805a-2f360993fca4.png">

(2) <img width="1914" alt="image" src="https://user-images.githubusercontent.com/96031300/185496906-b0032f0a-20f3-4ccf-af5f-3dadf3b4bf15.png">

(3) <img width="1914" alt="image" src="https://user-images.githubusercontent.com/96031300/185494992-7fb3aae7-232b-46c7-9a8e-2e2b1bc64e20.png">

### Version

2.0-alpha

### What browser are you seeing the problem on? What version are you running?

Opera GX [LVL4 {core: 89.0.4447.98) (x86_64)}

### Steps to reproduce

- Hover cursor over feature buttons on the right side of map.
- Open Map Data menu
> (1) Toggle Map Features individually, or Disable/Enable All (at the bottom of the list).
(2) Expand Style Options and check the box next to Highlight Changes.   

  

### The browser URL at the time you encountered the bug

https://mapwith.ai/rapid-v2-alpha#background=Maxar-Premium&datasets=fbRoads,msBuildings&disable_features=boundaries&map=2.00/0.0/0.0

**Comment by bhousel** [comment] 2022-08-19 16:19
Thanks for reporting @flow-enol 👍 
The Map Features aren't implemented yet in this alpha, so we'll add some UI hint to make that more clear.
This feature will make it into the v2 release in some form, we're still thinking through what it will look like.

**Comment by Bonkles** [comment] 2022-08-19 19:16
Okay! We added a label and disabled the entire control set just to make it clearer that this stuff shouldn't work. 

<img width="480" alt="image" src="https://user-images.githubusercontent.com/1887955/185691075-68216167-9809-4a60-8f8e-1793365f9198.png">

Also, this is a duplicate of another issue we already had in our backlog: #449. Closing this bug now that we've signalled this better in the UI.

**Closed by Bonkles** 2022-08-19 19:16 UTC

**Comment by Bonkles** [comment] 2022-09-12 18:10
Just a note to say that we have gotten this feature working once again in the alpha code. It should make the next release, which will be 2.01-alpha
