### ISSUE TITLE
ESRI/San Diego Missing Data

### ISSUE THREAD

**Issue by mds08011** [facebookincubator/RapiD#174] opened 2020-09-11 06:28 UTC
I suspect that the ERSI building outlines for San Diego County may not be showing all the data.  I compared the buildings in RapiD with the .shp files I had downloaded from SanGIS (ESRI's source) and noticed missing outlines in the few example areas I looked at.

All screenshots below pertain to this map area:
- RapiD Area: https://mapwith.ai/rapid-esri#background=Maxar-Premium&disable_features=boundaries&map=17.72/32.83305/-117.18084

- OSM Area: https://www.openstreetmap.org/#map=18/32.83281/-117.18125

.SHP data from SanGIS (no image background):
<img src="https://user-images.githubusercontent.com/8010709/92763121-155f8d80-f348-11ea-9d0b-9ee91eda9d33.png" width="80%">

.SHP data from SanGIS (with image background):
<img src="https://user-images.githubusercontent.com/8010709/92763138-198bab00-f348-11ea-9059-b230d108c114.png" width="80%">

RapiD Building Outlines:
<img src="https://user-images.githubusercontent.com/8010709/92763167-201a2280-f348-11ea-986c-ebad2d5f5098.png" width="80%">

RapiD Settings:
<img src="https://user-images.githubusercontent.com/8010709/92763187-23ada980-f348-11ea-8b33-73b0fe650d3e.png" width="80%">

**Comment by gaoxm** [comment] 2020-09-11 15:17
Thanks for reporting @mds08011! We'll look into this.

**Comment by Bonkles** [comment] 2020-11-05 14:45
Hi @mds08011 - I just took a look at the data myself and it looks like I can't reproduce the issue anymore- the buildings look like they're all there.  Two things are possible here- the service failed to retrieve some of the data and displayed a partial list, or the data was incomplete at the time you filed the bug and ESRI has since added it. :) 


![image](https://user-images.githubusercontent.com/1887955/98255680-a8353680-1f4b-11eb-8886-94c0ebeb22ba.png)

**Comment by Bonkles** [comment] 2020-11-05 14:46
Closing since I can't reproduce.

**Closed by Bonkles** 2020-11-05 14:46 UTC

**Comment by mds08011** [comment] 2020-11-18 05:38
Thank you for looking into it!  I am no longer able to reproduce either.
