### ISSUE TITLE
Suggesting already submitted buildings

### ISSUE THREAD

**Issue by kauevestena** [facebookincubator/RapiD#592] opened 2022-09-23 21:02 UTC
### Description

Hello Chris and RapID Team!! First of all, congratulatiions for the amazing work!!

I've submitted some edits, then the RapiD suggested again already mapped buildings, so it has been flagged as "building crosses building" as in the screeshot attached!

![bug report](https://i.imgur.com/YAeYyLV.png "suggesting aleady submitted buildings")

Fondly,
Kauê Vestena

### Version

2.0-alpha

### What browser are you seeing the problem on? What version are you running?

Firefox v105.0

### Steps to reproduce

- Submit (save) a building
- Go to the same one, 
- Accept it again

### The browser URL at the time you encountered the bug

https://mapwith.ai/rapid-v2-alpha#background=Maxar-Premium&datasets=fbRoads,msBuildings&disable_features=boundaries&map=20.47/-25.29910/-49.30551

**Comment by StephanGeorg** [comment] 2022-09-27 08:26
https://github.com/facebookincubator/RapiD/issues/601

**Comment by kauevestena** [comment] 2022-09-27 22:13
@Bonkles well, I did never noticed this behavior at the old RapID...

About your question, it was really right after, on the mentioned one.
But at the first time I've noticed, it may took 5 minutes or so, i'm not certain about the precise timing...

**Comment by Bonkles** [comment] 2022-09-28 14:27
Update: this is definitely NOT expected behavior. I suspect our service is caching OSM Data that it shouldn't be. Therefore, when it conflates against newly added buildings, it's still generating buildings and sending them to rapid according to stale OSM data. 

We have opened a priority investigation into this and will report back.

**Comment by Bonkles** [comment] 2022-09-28 14:56
Investigation started: 

I submitted a single building in RapiD City, SD, via URL https://mapwith.ai/rapid#background=EsriWorldImagery&datasets=fbRoads,msBuildings&disable_features=boundaries,past_future&map=18.17/44.10224/-103.20913

![image](https://user-images.githubusercontent.com/1887955/192812490-cfff671c-1ebd-4a42-a05d-47317f1c1262.png)

THe screen repainted after the submission, and no duplicate rapid building was observed. 

I then loaded the same area in safari, that worked fine too- no dupe buildings. 

It looks like this may be a difficult one to reproduce.

**Comment by StephanGeorg** [comment] 2022-09-28 15:30
I just tested it right now and it worked with v1.1.9 and v2-alpha. Maybe it was a performance issue because of high load to OSM servers?

**Comment by Bonkles** [comment] 2022-09-28 15:35
Thank you @StephanGeorg we were about to ask if you could reproduce the issue.  We suspect that load to OSM or unavailability to OSM could be causing this- we fail back to Overpass if OSM is unresponsive, and if overpass hasn't ingested the changes yet from OSM, it *could* cause this behavior. 

We re hatching a plan to provide the user with a hint of when conflation goes 'wrong' and wasn't able to get information from OSM in a timely fashion. This should hopefully provide a better UX and let you know when we think something went wrong. 

We will also put some better logging into our back-end service so that we can pinpoint the exact time(s) when these conflation requests have to resort to overpass downloads.

**Comment by Bonkles** [comment] 2022-09-28 16:32
Closing this one out, we'll take up the improvements in issue https://github.com/facebookincubator/RapiD/issues/602.

**Closed by Bonkles** 2022-09-28 16:32 UTC
Labels: bug
