### ISSUE TITLE
Unable to create a closed loop from a single line segment

### ISSUE THREAD

**Issue by bsidhuFB** [facebookincubator/RapiD#564] opened 2022-08-19 21:28 UTC
### Description

Understood that the area button is unavailable at this time. I was unable to create a closed loop from a single line segment. i was able to draw a single segment with 4 nodes and merge the last node to the first, but not able to double click on the first node to close a loop. 
![Screen Shot 2022-08-19 at 2 23 08 PM](https://user-images.githubusercontent.com/111467504/185709235-4ef3b7ee-47bd-4c9b-be59-37ce9e5a3d29.png)
![Screen Shot 2022-08-19 at 2 23 39 PM](https://user-images.githubusercontent.com/111467504/185709241-32b37aac-74fb-4f60-9ffe-bc5a9f9c5201.png)
![Screen Shot 2022-08-19 at 2 24 07 PM](https://user-images.githubusercontent.com/111467504/185709243-76242e7f-8556-4854-af33-bee82389e362.png)

### Version

2.0-alpha

### What browser are you seeing the problem on? What version are you running?

Chrome v104.0

### Steps to reproduce

1. Draw an are like a square
2. Double click on first node to close. (should just create an box with an open side)
3. Continue drawing from previous node and end near starting node
4. Select first and last node
5. Merge nodes (this creates a closed loop that is not an area)

### The browser URL at the time you encountered the bug

https://mapwith.ai/rapid-v2-alpha#background=Bing&datasets=fbRoads,msBuildings&disable_features=boundaries&map=20.73/37.57689/-122.03164

**Comment by Bonkles** [comment] 2022-09-15 17:20
Thank you for the bug! This is a duplicate of #561, so I am closing this issue and tracking the fix there.

**Closed by Bonkles** 2022-09-15 17:20 UTC
